### ISSUE TITLE
バージョン2

### ISSUE THREAD

**Issue by kentaiwami** [kentaiwami/masamon#104]
## アップデート内容
- [x] pdfでの取り込みは，pdf内の文字が記述されている場所をもとに判断して行うアルゴリズムへ変更．
- [x] スタッフ名を認識する方針を廃止する．あらかじめ入力しておいてもらう方針にする．
## TODO
- [x] 文字が記述されている箇所が一定の規則性をもっているかを過去のシフト表で調査する．
- [x] 重複して2次元配列に記録している配列を削除するメソッドを追加．
- [x] 同じ行と判断された配列同士を結合する．
- [x] 結合後の配列をx座標の昇順で並び替える．
- [x] 必要な行(配列)の範囲外の行(配列)を削除するメソッドを追加．
- [x] 日付だけが書かれた行(charinfo[])は削除される前に別変数で保存しておいて、後にやるx座標の処理に使用する。
- [x] 平成が書かれた行(charinfo[])はクール判定が終了したら削除されるようにする。
- [x] スタッフ名の1次元String配列と1日ごとのシフトを記録した2次元String配列を受け取って，スタッフ名:シフト名のように加工する．
- [x] 加工したデータをデータベースへ格納する．
- [x] 入力したユーザ名に該当するシフトから時給を計算して登録する．
- [x] シフト体制の登録・編集は名前とグループ名だけを入力させて，時間帯はグループから自動入力する．
- [x] スタッフが1名も登録されていない場合は，アラートを表示させて取り込み処理を行わないようにする．
- [x] 月ごとのシフト画面のボタンはその他を紫色に変更する．
- [x] スキップを押した場合は，該当する文字を"不明"に置き換える．
- [x] 保守用コードにデータベースのレコードをアップデートする処理を追記する．
- [x] スタッフ名を登録していない状態で取り込むボタンを押したらファイルを削除する．
