### ISSUE TITLE
月給表示画面

### ISSUE THREAD

**Issue by kentaiwami** [kentaiwami/masamon#17]
## TODO
- [x] ユーザ名だけ強調表示する :eyes: 
- [x] 画面レイアウトを設計
- [x] 月給の表示
- [x] データベースに日付だけでなく、年と月も記録する
  - [x] 11日が何月の11日なのかを判断する
  - [x] ShiftDetailDBへyear,monthを記録する
- [x] カレンダーのback,next,todayのみのボタンで誰が何のシフトかを表示
  - [x] ●月●日というテキストラベルを追加し、変更されるようにする
  - [x] ShiftDetailDBからスタッフのシフトを取ってくる
  - [x] 取ってきたシフトを早,中,中2,中3,遅で分けて表示する
  - [x] "今日"というボタンを押したら今日の日付を取ってきて、その日のシフトを表示をする。データがない場合はデータなしを表示。
  - [x] :arrow_forward: ボタンを押したら次の日の表示をする。データがない場合はデータなしを表示。
  - [x] :arrow_backward: ボタンを押したら前の日の表示をする。データがない場合はデータなしを表示。
