### ISSUE TITLE
PDFから取り込めるようにする

### ISSUE THREAD

**Issue by kentaiwami** [kentaiwami/masamon#67]
#### TODO
- [x] pdftestでやったことをまさもんでもやってみる 
- [x] クラス分けをして使用してみる
- [x] 2つのsample.pdfで問題なく1行ずつ抽出する
- [x] 1つ目の平成〜を記録している箇所を解析して、年月を判定する
- [x] ShiftDB,ShiftDetailDBへの記録
  - [x] 上書き処理と新規追加処理を分けて動作を確認する :eyes: 
- [x] スタッフ名にシフト名が含まれていた場合、シフト認識カウントが一致せず無限ループする 
  - [x] シフト認識のOKパターンを実装 
  - [x] 認識ができたシフトを削除したテキストをalertのmessageとして表示する
  - [x] シフト認識のNGパターンを実装
    - [x] データベースへ新しいシフトを登録する
  - [x] シフトインポート画面でPDFならPDFmethodを実行するようにする
  - [x] スタッフ名認識のNGパターンを実装
  - [x] alertがあとどのくらい出てくるのかを数値として表示する 
  - [x] alert表示中、returnキーをnextキーに変えれないか検討
  - [x] ShiftSystemDBの再構築を行う
  - [x] HolidayDBの追加と組み込み
- [x] スタッフ名の抽出を行っているメソッド内にある、othershiftをデータベースから取得するように変更する
- [x] シフトインポート画面を呼び出しで同様に処理を行う
- [x] その他のシフトが"他"で記録されてしまっているので、シフト名を記録するようにする
- [x] 中番を単純に引き算しているが、他のシフトパターンが来た際に対応できない
- [x] 夏休1日消化などの文字があるとそれをカウントしてしまう
